name: Build and Deploy

# TODO VOODOO temp dev verification
on: push
# Runs build and deploy whenever main is merged to or pushed to.
# (...please don't push directly to main)
# on:
#   push:
#     branches:
#       - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node/NPM
        uses: actions/setup-node@v3
        with:
          # Just picked what we've been using in local dev work
          node-version: 18
      - name: Install node modules
        # `npm ci` tells npm to install matching against package-lock file
        run: npm ci
      - name: Setting up Vite env vars
        env:
          GALAGO_MULTI_LINE_TEST: ${{ secrets.GALAGO_VITE_ENV_VARS }}
        run: |
          echo "VOODOO preexisting contents of .env file"
          cat .env
          echo Setting up Vite env vars file
          echo "$GALAGO_VITE_ENV_VARS" > .env
      - name: VOODOO troubleshooting env vars not working
        run: |
          pwd
          ls -al
          sed -n 1p .env
          sed -n 2p .env
          sed -n 3p .env
          sed -n 4p .env
          sed -n 5p .env
          sed -n 6p .env
          sed -n 7p .env
          sed -n 8p .env
          sed -n 9p .env
          sed -n 10p .env
          echo "echoed lines, how did it go?"
      - name: Build app
        # As configured in Aug 2022, `vite build` outputs to `dist` folder.
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # see above, default output folder for `vite build`
          # By default, deploys branch to `gh-pages`, but let's be explicit
          branch: gh-pages
