name: Build and Deploy

# For development, just run on push to any branch
on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node/NPM
        uses: actions/setup-node@v3
        with:
          # Just picked what we've been using in local dev work
          node-version: 18
      - name: Install node modules
        # `npm ci` tells npm to install matching against package-lock file
        run: npm ci
      - name: Build app
        env:
          # This is not really a "secret", just a way to get per-repo env vars.
          # Annoyingly (but reasonable), GitHub redacts this from logs, so you
          # won't be able to see the build mode by reading the Action's logs.
          GALAGO_VITE_BUILD_MODE: ${{ secrets.GALAGO_VITE_BUILD_MODE }}
        # As configured in Aug 2022, `vite build` outputs to `dist` folder.
        run: npm run build -- --mode $GALAGO_VITE_BUILD_MODE
      - name: Quick check of multi-line secrets
        env:
          GALAGO_MULTI_LINE_TEST: ${{ secrets.GALAGO_MULTI_LINE_TEST }}
        run: |
          echo trying to drop in value
          cd dist
          ls -al
          echo $GALAGO_MULTI_LINE_TEST > .env
          echo "$GALAGO_MULTI_LINE_TEST" > .otherenv
          echo let us see the results
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # see above, default output folder for `vite build`
          # By default, deploys branch to `gh-pages`, but let's be explicit
          branch: gh-pages
