name: Build and Deploy

# For development, just run on push to any branch
on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node/NPM
        uses: actions/setup-node@v3
        with:
          # Just picked what we've been using in local dev work
          node-version: 18
      - name: Check NPM status
        run: |
          echo Checking npm status...
          npm --version
          echo well that's good
