name: Build and Deploy

# For development, just run on push to any branch
on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Verify npm not installed
        run: |
          echo Checking npm status...
          npm --version
          echo huh, made it