name: Build and Deploy

# For development, just run on push to any branch
on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node/NPM
        uses: actions/setup-node@v3
        with:
          # Just picked what we've been using in local dev work
          node-version: 18
      - name: VOODOO verify failure stops script
        run: |
          echo gonna fail now
          exit 1
          echo this will not be written
      - name: VOODOO check on failure
        run: |
          echo the next step after failure
          echo did not echo right right
      - name: Install node modules
        # `npm ci` tells npm to install matching against package-lock file
        run: npm ci
      - name: VOODOO verify node modules install
        run: |
          echo checking node install...
          ls -al
          ls -al node_modules
      - name: Build app
        # As configured in Aug 2022, `vite build` outputs to `dist` folder.
        run: npm run build
      - name: VOODOO verify build ran
        run: |
          echo checking build...
          ls -al
          cd dist
          ls -al
