name: Build and Deploy

# For development, just run on push to any branch
on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Okay that blows my mind
          echo you can edit the running workflow from a branch
